export { default as ProfInput } from './ProfInput'
export { default as ProfInput2 } from './ProfInput2'
export { default as ProfLabels } from './ProfLabels'
export { default as ProfNav } from './ProfNav'
export { default as ProfUploadFile } from './ProfUploadFile'
export { default as ProfUploadImg } from './ProfUploadImg'