export { default as BaseMessage } from './BaseMessage'
export { default as MajorCategory } from './MajorCategory'
export { default as MajorField } from './MajorField'
export { default as PersonHistory } from './PersonHistory'
export { default as PersonOpinion } from './PersonOpinion'
export { default as FinishApply } from './FinishApply'